### ISSUE TITLE
你好，我想问下，您上传的这个版本一开始训练有很多参数要调吗？我加了你文中提到warm_up，但是训练结果永远都只有0.84左右，到不了视频分享中的0.95，0.96左右再开始冻结backbone，yolo_head的精调阶段。

### ISSUE THREAD

**Issue by XuanheLiu** [LKKlein/AI-Insects-Challenge#2]

**Comment by LKKlein** [comment]
@XuanheLiu 不好意思哈，其实我这个版本只是最后用来精调使用的，因为这样自定义训练起来会很方便，前期的训练我都是用[PaddleDetection](https://github.com/PaddlePaddle/PaddleDetection)完成的。
我也没有尝试过用这个版本从头开始训练，但是从理论上来说，这里的实现跟PaddleDetection并没有什么区别，只是从中抽取了必要的模块，原理上更容易理解而已。如果你有兴趣的话，可以和我一起看一看代码中会不会有什么缺漏的部分。
如果你还想继续尝试从头开始训练的话，可以考虑修改修改学习率、动量、数据增强方法及参数等等，但我并不能保证一定有效果。后面等有时间，我会考虑在这个版本训练一下。

**Comment by XuanheLiu** [comment]
@LKKlein 嗯嗯 好的   我以为一开始就是这个呢  不过我没训出来，也许是自己调的参数有问题  那我拿先在PaddleDetection上再试试   谢谢及时回复

**Comment by XiminLin** [comment]
@XuanheLiu 请问你用 PaddleDetection 上试出来了吗? 我在 PaddleDetection 上面试, 从用 imagenet 的 weights 初始化训练的话, 最高的 validation mAP 也只有 58 左右. 模型不加任何 freeze, 加了 augmentation 的操作 和 warm up 和 cosine decay, 请问你们是怎么训练的?
