### ISSUE TITLE
关于mean配置

### ISSUE THREAD

**Issue by xmy0916** [LKKlein/AI-Insects-Challenge#4]
mean: [231.448, 236.276, 235.433]您好能问下您这些mean的参数您是怎么求得的吗，他是训练集图片三个通道的均值吗？

**Comment by LKKlein** [comment]
是的，用训练集求所有图片三个通道的均值和方差，网上有这方面的代码，你可以找一下。  
不过，其实这个参数的影响不是特别大，你用imagenet的均值也是可以的，只要保证训练和测试的时候相同就行。

**Comment by xmy0916** [comment]
好的，谢谢！
